### ISSUE TITLE
Appimage not working since 2.0.5 on Qnap HDStation (ubuntu 1804)

### ISSUE THREAD

**Issue by nephaste** [oscartbeaumont/ElectronPlayer#33]
Hi i am a third part developper for Qnap NAS

many user report me that since you update to 2.05 application do not start anymore
2.0.4 started well (but Netflix stopped working as you noticed it that why i updated the Qnap package)

Qnap HDStation is an Ubuntu 1804 x86_x64...
when you start it nothin happen... nothin in dmesg as well...
not sure how i can debug it....  may be the Electron version is not supported by Ubuntu 1804 .. but really not sure...

i wonder if you can help me to solve this issue

**Comment by nephaste** [comment]
did a yarn build to test non appimage (direct linux version) from an ubuntu 1404 .. same issue
it seems starting but ... nothin.... no error message

i will try to built it directly on Ubuntu 1804

**Comment by oscartbeaumont** [comment]
The previously latest version of the snap is broken everything else should work. If you don't know the still occurring events for this repo a quick recap is. Last Friday (possible earlier) Netflix published an update to their frontend that didn't support the old version of Chrome (Electron) this app used due to the Netflix DRM not liking the newer version. Sunday I pushed an update to fix that and the module I used to fix it doesn't play well with the Snap sandboxing and so the snap app broke, I then rolledback back to the release with broken Netflix so people can still use the app. I am working to fix that issue before releasing the patch but the bug is out of my hands in an upstream closed source repo. Everything has been an absolute mess. I have been using the Mac and testing the normal Linux version and they are fine it was just the snap to my knowledge.

**Comment by oscartbeaumont** [comment]
`2.0.4` = Working app, broken Netflix player
`2.0.5` = Fixes Netflix Player, breaks the snap version of the app
`2.0.6` = A tired me does a stupid thing to try and fix the snap version which fails and gets blocked by snapcraft and so was never released to any devices via snapcraft.
I had to go to bed so rolled the stable back to 2.0.4 with only ~300 devices installed my fauly snap update.

**Comment by nephaste** [comment]
thanks for message... i tried to yarn build directly on ubuntu 1804

`root@bionic:/SRC/ElectronPlayer# yarn build
yarn run v1.16.0
$ electron-builder -p never
  • electron-builder version=20.43.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist/builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=linux arch=x64 electron=5.0.4 appOutDir=dist/linux-unpacked
  • downloading               parts=8 size=66 MB url=https://github.com/electron/electron/releases/download/v5.0.4/electron-v5.0.4-linux-x64.zip
  • downloaded                duration=20.936s url=https://github.com/electron/electron/releases/download/v5.0.4/electron-v5.0.4-linux-x64.zip
  • building        target=AppImage arch=x64 file=dist/electronplayer 2.0.6.AppImage
  • building        target=snap arch=x64 file=dist/electronplayer_2.0.6_amd64.snap
  • downloading               parts=1 size=1.5 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-9.1.0/appimage-9.1.0.7z
  • downloading               parts=8 size=47 MB url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-2.4/snap-template-electron-2.4.tar.7z
  • downloaded                duration=1.974s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/appimage-9.1.0/appimage-9.1.0.7z
  • downloaded                duration=15.894s url=https://github.com/electron-userland/electron-builder-binaries/releases/download/snap-template-2.4/snap-template-electron-2.4.tar.7z
Done in 107.69s.
`
same issue .. with AppImage and Linux x64 version   :(

seems starting but nothing (process not start) tried on an ubuntu 1804 and on the native Qnap HDStation

**Comment by oscartbeaumont** [comment]
That's very odd, I will have to look into it.

**Comment by nephaste** [comment]
thanks for the 2.0.7 but same issue.. with AppImage  :(

I have no clue... supspecting a bug with latest Electron but not sure

**Comment by oscartbeaumont** [comment]
Are you running the app in a confined environment?

**Comment by nephaste** [comment]
yes... HDStation is an LXC container.... and my Ubuntu1804 for test as well

**Comment by nephaste** [comment]
After some research i found the issue, you need to add --no-sandbox

./electronplayer.2.0.7.AppImage --no-sandbox

all is working fine  refering this post https://github.com/electron/electron/issues/17972

**Comment by oscartbeaumont** [comment]
That is probably the cause of the problem. The reason it is not launching is due to the Chrome sandbox which is now enabled by default in the latest version of Electron and it is trying to use instructions that are being blocked in that environment. Due to the snap being a sandbox in itself `electron-builder`'s fix was to just disable the Chrome sandbox for the snap release package and this fixed the problem. If you contact me personally I would love to build the Qnap package into the official releases of ElectronPlayer just to keep a consistent and reliable brand and fix this bug.

**Comment by nephaste** [comment]
thanks... actually qpkg built is a bit tricky... i am working for Qnap and also for Qnapclub

Electron Player is currently available for everyone here : https://www.qnapclub.eu/fr/qpkg/737

thanks again for all
