### ISSUE TITLE
My fork with Windows support

### ISSUE THREAD

**Issue by TheRolfFR** [oscartbeaumont/ElectronPlayer#35]
Hey, I discovered your player and made a fork of it with Windows and a new design:

[https://github.com/TheRolfFR/ElectronPlayer](https://github.com/TheRolfFR/ElectronPlayer)

![ElectronPlayer Menu](https://raw.githubusercontent.com/TheRolfFR/ElectronPlayer/master/docs/ElectronPlayer.png)
_New design I made_

I use Castslabs version of widevine.
The only problem is that legally we can run it in developer mode but in production we must ask Widevine to provide a license to sign it.
If some of you wants to help me, or else please respond to this "issue".

Thanks in advance.

**Comment by oscartbeaumont** [comment]
Is it possible for you to provide me with a source for where it says it is legally required to run with a licence in production? The Linux version of this application currently uses it without a Widevine certificate (using the default development certificate) and it works but this approach isn't working on MacOS. I applied for a Widevine certificate and have not gotten a rely. It has been a very long time since I applied and I am not expecting to get a certificate after reading other peoples experiences with Electron, Widevine and small open source projects. If I am not allowed to legally use the development certificates I will have to look for an alternate solution. My understanding was that some services require the production certificate which could be why the castlabs electron doesn't work on MacOS but the certificate wasn't necessarily legally required.
I will look into adding Windows support in the next release, The only reason Windows is not currently supported is the old Widevine package didn't support Windows but after the recent changes to the handling of Widevine as you have shown in your fork, it is now supported.
I also think your menu styling changes look cool but I would prefer to keep the black/grey colour scheme due to it fitting in with the Netlfix colour scheme much better (which is my main use of the app). Do you think some options to be able to modify the menu's colour/layout would suit? Maybe even a couple of default layouts as well included like the original black/grey and your lighter green one?

**Comment by TheRolfFR** [comment]
Here the link saying that signing is required for production: [https://github.com/castlabs/electron-releases#licensing](https://github.com/castlabs/electron-releases#licensing)

What is written is that it is signed for development but not for production and you'll have to resign it. That's why I am recommanding to clone the repo and possibly make a bash or bat file to run it in dev.

There is no problem with the color scheme that can be changed in the options. I tired to reput all the features but I have no idea what is the PictureInPicture and how it works.

If your cloned my repo, you must have seen the settings menu and yes we could add themes or layouts.

**Comment by oscartbeaumont** [comment]
Have you checked Netflix compatibility because it is not working on my system with your fork? It is doing the same thing as MacOS does with castlabs-electron.

**Comment by TheRolfFR** [comment]
No I don't have a Netflix account or a MacOS with me but on Windows, Spotify seems to work properly and I tried VOD and it works. I will try to set up a virtual machine.

Currently I am working on the themes

**Comment by oscartbeaumont** [comment]
Theming and Windows support would also be awesome but unless it can run all of the default services, I can't officially support it. Widevine DRM is the main limiting factor of Windows support but I will keep on the lookout for ways to run Widevine on Windows.
