### ISSUE TITLE
Developer menu shown

### ISSUE THREAD

**Issue by b3nvo** [oscartbeaumont/ElectronPlayer#37]
Hi,

i'm using Zorin OS 15. The application initially didn't work when installed through the software center (the ubuntu software center). Using snap i managed to get it installed after quite a while. After initially opening the app and noticed the Developer menu item with all its functionalities still working.

it's not much of an issue, but not something you'd permanently want in your application.

**Comment by oscartbeaumont** [comment]
This was intentional but thanks for reporting it. I left it in for two main reasons.
1) I envision the app being used by the more tech-savvy people who would benefit from the extra options to debug problems like pages not loading. It also benefits me if someone reports a problem it might be easier for them to get information that can help me with the issue.
2) Chrome ships with debugging tools enabled by default and since ElectronPlayer is like a browser designed for media content I see it fitting to keep it enabled.
I also do not see a danger in keeping it enabled as people who don't understand the developer tools will just ignore the option and it causes no harm. If there is a major danger in leaving devtools enabled I would be happy to remove it but there shouldn't be one if Chrome made the decision to keep it enabled.
