### ISSUE TITLE
Can't run directly

### ISSUE THREAD

**Issue by FromOopsToOps** [oscartbeaumont/ElectronPlayer#42]
Hi folks,

I'm running on an issue while trying to run electronplayer. Executing it directly from terminal renders me with a "failed: no such file or directory" result. Although, trying to run it from the actual executable (/snap/electronplayer/current/electronplayer) it works.

I'm not sure where to start to hunt the problem down, any suggestions?

I'm using Gentoo.

**Comment by oscartbeaumont** [comment]
I would have no clue what's causing this but I would **assume** it would be an issue is in `electron` (the old version this project uses) or `electron-builder`. I currently don't have a working Linux system but hopefully, within the week I will and I will try and reproduce and debug the problem.
Just so I understand why can't you just launch it from the executable?

**Comment by FromOopsToOps** [comment]
If I try to run from the applications menu, nothing happens. Running "electronplayer" from terminal gives me:

```
execl failed: No such file or directory
child exited with status 1
```
If I run through `/snap/electronplayer/current/electronplayer`, everything works as expected.

I don't have electron nor electron-builder installed right now, but if that helps to understand the problem, I can install it. Is there any log I can watch in the meantime?

**Comment by oscartbeaumont** [comment]
Ok so I had a look and it must just be your Linux environment. I am running a near fresh install (~1 day old with a few snap's and Virtualbox installed) of PopOS 19.04 and I can run the command `electronplayer` to start the app and it works fine. I have the latest update of ElectronPlayer installed via Snapcraft. When I run `/snap/electronplayer/current/electronplayer` the app doesn't show any services which my guess would be because it is running outside of the snap confinement due to me directly running the binary and it not finding a config file.
I recommend researching this issue in your Linux environment and if it is being caused by the app not your environment please reopen the issue. Sorry to not be able to help more.
