### ISSUE TITLE
macOS binary "outdated"

### ISSUE THREAD

**Issue by Rastafabisch** [oscartbeaumont/ElectronPlayer#45]
Hi there! 

Would it be possible to issue a current macOS build including the latest features, which the latest available one doesn't?
I just can't succeed building my own.

Thank's for keeping up your great work!
Best,
Rastafabisch

**Comment by oscartbeaumont** [comment]
Yes, I am aware, I have been busy and haven't had time to thoroughly test the app before re-releasing it for Linux and Mac (as I use a build system the releases are synced). I will do this over the next couple of days.
I have also been putting it off because I am about to release a new version of the Mac app on a new core which will be released when I finish it.
Sorry, it has taken me so long to reply, I drafted this message and completely forgot to press send.

**Comment by oscartbeaumont** [comment]
Fixed when releasing v2.0.8
