### ISSUE TITLE
syntax for config.json?

### ISSUE THREAD

**Issue by neogeo71** [oscartbeaumont/ElectronPlayer#67]
Can I please get an example of the new syntax for the config.json? I cannot get it right for the life of me.

I want to add some services, and play with the browser agents.

Looking forward to the gui to add these easily.

**Comment by oscartbeaumont** [comment]
You can view the default services included in the app [here](https://github.com/oscartbeaumont/ElectronPlayer/blob/master/src/default-services.js) to get an idea of the json schema. Hopefully the next update will move to a user interface for managing services to fix issues like this.

**Comment by neogeo71** [comment]
I looked at this prior to positing. Using this It still resets every time to default. I am not sure what I am am doing wrong.

**Comment by oscartbeaumont** [comment]
The color can be any colour in css format. These formats can be viewed [here](https://developer.mozilla.org/en-US/docs/Web/CSS/color).

The logo must be a URL or relative path if the icon is included within the app (only the default services). As a tip you can use `file://` urls to specific icons that are stored on your computer hence don't have a public url or you can just use `https://` or `http://`.

Take note of commas and quotes used in this example as they are usually the cause of mistakes in JSON. Sorry about the config resetting itself on error, it is handled by an external package and this behaviour I can't override. It will be fixed in a future update and this is being tracked in issue #61.

Hopefully this example which takes you straight to some Netflix categories demonstrates the config format. You should be able to replace your entire config with this and start the app and it should work. Please confirm you have the latest version of the app (`2.0.8`) if you are still having issues.
```json
{
	"version": "2.0.8",
	"services": [
		{
			"name": "Netflix TV Shows",
			"logo": "services/netflix.png",
			"url": "https://www.netflix.com/browse/genre/83",
			"color": "#e50914"
		  },
		  {
			"name": "Netflix Movies",
			"logo": "services/netflix.png",
			"url": "https://www.netflix.com/browse/genre/34399",
			"color": "#e50914"
		  }
	]
}
```
