### ISSUE TITLE
Linux: Browser Unsupported

### ISSUE THREAD

**Issue by sakakun** [oscartbeaumont/ElectronPlayer#70]
OS: Linux Mint 19.3
Service: Youtube (Not the YouTube TV)

Warning appears that the browser is unsupported and recommends that it should be upgraded to a newer version.  Also can't login for the same reason.

**Comment by oscartbeaumont** [comment]
Are you running the latest version of the app because the newest version, although I don't think is the exact newest chrome version, it should be close.

**Comment by sakakun** [comment]
We'll now it won't even let me log in... 
```
This browser or app may not be secure. Learn more

Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
```

**Comment by oscartbeaumont** [comment]
The Google login issue is #40 and will be fixed in the next release. I think the original issue will also be fixed by the same change so I am going to close this issue and you should subscribe to #40 to know when a new release is out fixing the issue. I have been really busy so it may be a while before I release an update.
