### ISSUE TITLE
Plans to add Hulu?

### ISSUE THREAD

**Issue by navyguns** [oscartbeaumont/ElectronPlayer#9]
Netflix works great! Any plans on adding Hulu? Thanks for your work.

**Comment by oscartbeaumont** [comment]
Can you go to the setting menu item in ElectronPlayer and click `Edit Config`. It will open the config in your systems text editor and can you add the Hulu entry as shown below under the Floatplane entry. Then save and restart ElectronPlayer it will then show Hulu in the GUI (with a Floatplane logo for now). Can you then login and tell me if it can play video correctly. If it can I would be willing to accept this change upstream, otherwise, more work needs to be done to handle Hulu's DRM. I do not have a Hulu account which is why I need someone else to do this.
```json
{
    "name": "Floatplane",
    "logo": "services/floatplane.png",
    "url": "https://floatplane.com/"
},
{
    "name": "Hulu",
    "logo": "services/floatplane.png",
    "url": "https://hulu.com/"
}
```

**Comment by navyguns** [comment]
I followed the steps as instructed. The Hulu entry appeared in the GUI
dashboard. When clicked, the Hulu homepage appeared. I was able to log
in to Hulu, select the current user from the list of users on my
account.

Attempting to play a video failed with an error message stating that my
web browser was out of date giving a link to Hulu system requirements:

Software
Mac OS X 10.9 or above, Microsoft Windows 10, and Chrome OS
Safari 11 or above, Firefox 65 or above, Chrome 69 or above, and
Microsoft Edge on Windows 10
HTML5 enabled
JavaScript and Cookies enabled

Attached is a hulu.png logo if you need one.

-----Original Message-----

**Comment by oscartbeaumont** [comment]
I just used the Floatplane logo as I expected it to not work as @austinkregel originally had Hulu in his PR and it was removed. I really want to be able to support as many streaming services as possible but Hulu will not currently be able to be added due to the old browser version used by ElectronPlayer. ElectronPlayer uses an older version of Electron and hence Chromium (66.0.3359.181) so that the Netflix DRM can work. I accually think Hulu uses the same DRM but I could be wrong. The details about why I can't upgrade are detailed in issue #2. I will revisit this if issue #2 is ever resolved but annoyingly I doubt it ever will.

**Comment by oscartbeaumont** [comment]
Sorry, forget everything I just said. I just went looking again and found a solution that works with Chrome 69 for Widevine, I will push an update soon and once I push it you can try Hulu again and once Hulu is working I can add it to the default services.

**Comment by oscartbeaumont** [comment]
Can someone please update and try Hulu again because I recently did some major Electron (Browser) updates that. I would really like to add this as I have seen quite a few people requesting it.

**Comment by navyguns** [comment]
I just tried out the appimage on OpenSuse Leap 15.2 Mate desktop and Hulu worked flawlessly. I'll try it out on Mint Cinnamon later today and report back. Thanks for the work. Throw in a logo and it will look great.

**Comment by navyguns** [comment]
Tried Hulu on Linux Mint 19.1 with Cinnamon 4.0.10. Works like a champ.

**Comment by oscartbeaumont** [comment]
Thanks, I will look at adding it over the next few days as I need to push an update for a few other things.

**Comment by navyguns** [comment]
Tried the snap version on Linux Mint 19.1 Cinnamon (different computer than the earlier device) and received the "need to update browser error". Was the snap version not updated?

**Comment by oscartbeaumont** [comment]
I have added it to the default apps and it will be pushed in the next update. When it is released can someone please report back and confirm its functionality as I can't test it myself. If there is also someone with a Mac can they verify it works as I have a feeling it may not (It runs an older version of Electron than the Linux version for now).

**Comment by navyguns** [comment]
The snap version now works on Linux Mint 19.1 Cinnamon and the Hulu icon is in place on the screen. Thank you.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by navyguns** [comment]
I just added https://www.bitchute.com/ to the menu and it works just fine.

**Comment by navyguns** [comment]
I just added https://www.vimeo.com/ to the menu and it works just fine.
