### ISSUE TITLE
It does not start in Ubuntu 20.10

### ISSUE THREAD

**Issue by sronweb** [oscartbeaumont/ElectronPlayer#91]
Actually it's not starting anymore. 
If I lanch from terminal I see:

Gtk-Message: 20:25:01.212: Failed to load module "appmenu-gtk-module"

(electronplayer:13871): Gtk-WARNING **: 20:25:01.226: cannot open display: :0

If I check for the presence of the appmenu-gtk-module apparently seems to be installed:

apt-file search appmenu-gtk-module
appmenu-gtk-module-common: /usr/lib/systemd/user/appmenu-gtk-module.service
appmenu-gtk-module-common: /usr/share/doc/appmenu-gtk-module-common/changelog.Debian.gz
appmenu-gtk-module-common: /usr/share/doc/appmenu-gtk-module-common/copyright
appmenu-gtk2-module: /usr/lib/x86_64-linux-gnu/gtk-2.0/modules/libappmenu-gtk-module.so
appmenu-gtk3-module: /usr/lib/x86_64-linux-gnu/gtk-3.0/modules/libappmenu-gtk-module.so 

Please, is it due to some recent updates? Thanks

Ubuntu 20.10
Installed from snap

**Comment by oscartbeaumont** [comment]
It would not have been caused by a recent update as I have not updated this app in over two years. I am going to work on a new version of the app very soon though.
I found [this](https://askubuntu.com/questions/1074926/failed-to-load-module-appmenu-gtk-module-canberra-gtk-module) StackOverflow topic from the first error, as I don't have the issue myself I can't test if this would help. You will have to research the errors as I think the issue would be with your system, given the app is working on many other machines without a problem.
If you were not aware the application is built using [Electron](https://www.electronjs.org), and that is what these errors are coming from so that may help in your research.
If you can't work it out my only recommendation would be to reinstalled Linux but this is obviously not optimal.

**Comment by sronweb** [comment]
Thanks.
I have tried some steps about reinstallation of appmenu-gtk-module and it was not working.
Then I checked about the second part of the message "Gtk-WARNING **: 20:25:01.226: cannot open display: :0" and I realized that, as I have installed wayland, xfce etc I was in wayland and then restarted ubuntu in default configuration (I guess it used xorg, not sure) and now it's working! Thank you very much for your reply. I will look forward to next upgrade.
